### ISSUE TITLE
Doesn't work with testQuick

### ISSUE THREAD

**Issue by gabadi** [sbt/sbt-mocha#10]
When i run a normal test, everything works perfectly.

But when a run a testQuick, doesn't run anything.

That could be because the sbt-mocha plugin doesn't has any sbt.testing.Framework implementation

**Comment by huntc** [comment]
I'm unsure what's happening there... perhaps we need to go further with sbt testing here. I'd welcome a PR though. :-)

**Comment by gabadi** [comment]
I've an idea about how to do a simple version. I'll see if i can make it the next week or the other

**Comment by centaure** [comment]
Not sure if this helps, but I encountered the same problem when trying to get test-quick work with Jasmine (sbt-jasmine-plugin https://github.com/guardian/sbt-jasmine-plugin). As a quick fix, I added the following to my project's build.sbt:

(testQuick in Test) <<= (testQuick in Test) dependsOn(jasmine) dependsOn((testQuick in Test).toTask(""))

I am sure you can do something similar for mocha.

The above seems to do what I want it to do. But it probably can be worked on a bit more.

**Comment by jroper** [comment]
`testQuick` looks at the analysis from Java/Scala compilation, builds a dependency tree all the way to the tests, and then uses that to decide which tests should run. Since mocha tests are written in JavaScript, and JavaScript isn't compiled, there's no way to calculate such a dependency tree, and so `testQuick` could never be implemented. And so there's no conceivable way that this could be implemented in any way that makes sense, you could either run all the tests, or run none of the tests, but neither of those fits the definition of what `testQuick` is meant to do.

If you want to run all mocha tests when you run `testQuick`, then you can create an alias that runs `all testQuick mocha` to do this for you. I think having it explicit like that is a better default than forcing the run of all mocha tests on every `testQuick` run even when no JavaScript files have changed.
